// START:twitter
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package twitter

type Tweet struct {
	Message string `protobuf:"bytes,1,opt,name=message,proto3"
json:"message,omitempty"`

	// Note: Protobuf generates some fields and methods
	// for it to use internally, not including them for brevity.
}
// END:twitter
