// START:twitter
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package twitter

type Tweet struct {
	Message string `protobuf:"bytes,1,opt,name=message,proto3"
json:"message,omitempty"`
	// Note: Protobuf generates internal fields and methods
	// I haven't included for brevity.
}

// END:twitter
