// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: example.proto

package example

// ...

func (t *Person) Set(v string) {
	t.id = v
}

func (t *Person) Set(v string) {
	t.name = v
}

func (t *Animal) Set(v string) {
	t.name = v
}
